### PR TITLE
ProDark and Behave Dark overlay fixes...

### PR DESCRIPTION
**Pull request by Syres916**
..as well as ProDark red drop down boxes and Start module bypass.

Current ProDark toolbars:

CurrentProDarkIssue

with fix applied:

AfterFixProDark

Basically in the move from _FreeCAD/FreeCAD_ repository to _FreeCAD/FreeCAD-themes_ the links to the icon images has been broken so it seemed far easier to bring over the _images_dark_light_ folder with new logo backgrounds and correct all references in the qss files.

The Dark-contrast, Dark-modern, Darker and Light-modern will follow next week. 

All the above has been tested using:

```
OS: EndeavourOS (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38259 (Git)
Build type: Release
Branch: main
Hash: c8046b1c60c786caca3050cf51f853454ffb5388
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Behave-Dark-Colors 0.1.1
  * FreeCAD-themes 2024.7.24
```

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38265 (Git)
Build type: Release
Branch: main
Hash: 608cb182e516e683befa890a84ca615c040b1235
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * FreeCAD-themes 2024.7.24

```

### CODE REVIEW

**Comment by kadet1090** [comment]
Looks good! I only wonder if we should place the images in the `images_dark-light` folder which is also present in the main repository? From what I understand this can overwrite (or be overwritten by?) the files from core as it lives in basically one global search path?

I'll check it later today but maybe you know if my understanding is ok or flawed.

**Comment by Syres916** [comment]
I think I know what you are getting at, maybe this `post.FCMacro` that I've been playing with locally might explain what I've found:

```
# Classic theme must delete any set value for the editor text so that it is calculated dynamically when needed
import FreeCAD

appPrefs = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/General")
appPrefs.RemString("QtStyle")

import os

originalList = ["close.svg", "overlay.svg", "float.svg", "autohide.svg", "edithide.svg", "editshow.svg", "mode.svg", "taskshow.svg"]

for eachFile in originalList:
    if os.path.exists(
        FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/old" + eachFile
    ) and os.path.exists(
        FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/" + eachFile
    ):
        os.remove(
            FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/old" + eachFile
        )
        os.rename(
            FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/" + eachFile,
            FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/old" + eachFile,
        )
        FreeCAD.Console.PrintLog(
            "Removed existing file and renamed "
            + FreeCAD.getResourceDir()
            + "Gui/Stylesheets/overlay/icons/"
            + eachFile
            + " to old"
            + eachFile
            + "\n"
        )
    elif os.path.exists(
        FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/" + eachFile
    ) and not os.path.exists(
        FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/old" + eachFile
    ):
        os.rename(
            FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/" + eachFile,
            FreeCAD.getResourceDir() + "Gui/Stylesheets/overlay/icons/old" + eachFile,
        )
        FreeCAD.Console.PrintLog(
            "Renamed "
            + FreeCAD.getResourceDir()
            + "Gui/Stylesheets/overlay/icons/"
            + eachFile
            + " to old"
            + eachFile
            + "\n"
        )
    else:
        pass


```

**Comment by Syres916** [comment]
@kadet1090 Can you please let me know how this can proceed, feel like I'm in no-mans land at the moment?

**Comment by kadet1090** [comment]
I'm so sorry for taking so long! I had it on my todo list and it got flooded with other stuff and somehow I checked it as done. 

Yes, I checked and it looks fine - if the icons would prove to be problematic we can always change it later. 

Sorry again for tardiness.

**Review by kadet1090 — APPROVED** [review]

**Pull request merged**
